(* Emlang Grammar - Version 0.1 *)
(* EBNF notation following ISO/IEC 14977 *)

document        = block , { separator , block } ;

block           = flow | test ;

separator       = "---" ;

(* Flows *)
flow            = "/" , flow_name , "/" , newline , flow_content ;

flow_name       = name_char_ext , { name_char_ext } ;

flow_content    = sequence , { indent , separator , newline , sequence } ;

sequence        = { indent , flow_element , newline } ;

flow_element    = trigger | command | event | exception | view ;

(* Tests *)
test            = "?" , name , "?" , newline , test_content ;

test_content    = { indent , test_element , newline } ;

test_element    = command | event | exception | view ;

(* Elements *)
trigger         = "%" , [ swimlane , ":" ] , name , "%" , [ newline , attributes ] ;

command         = "[" , name , "]" , [ newline , attributes ] ;

event           = "<" , [ swimlane , ":" ] , name , ">" , [ newline , attributes ] ;

exception       = "!" , name , "!" , [ newline , attributes ] ;

view            = "{" , name , "}" , [ newline , attributes ] ;

(* Attributes *)
attributes      = { indent , indent , attribute_line , newline } ;

attribute_line  = free_text ;

free_text       = { any_char - newline } ;

(* Swimlanes *)
swimlane        = name ;

(* Names *)
name            = name_char , { name_char } ;

name_char       = letter | digit | "-" | "_" | "." ;

name_char_ext   = name_char | "/" ;

(* Comments *)
comment         = ";" , { any_char - newline } ;

(* Basic tokens *)
letter          = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j"
                | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t"
                | "u" | "v" | "w" | "x" | "y" | "z"
                | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J"
                | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T"
                | "U" | "V" | "W" | "X" | "Y" | "Z" ;

digit           = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

indent          = "  " | "\t" ;

newline         = "\n" | "\r\n" ;

any_char        = ? any Unicode character ? ;
